openapi: "3.0.0"
info:
  version: 1.0.0
  title: KB API
  license:
    name: Apache 2.0
servers:
  - url: https://kb.dk/api
basePath: /v1
paths:
  /hello:
    get:
      summary: Request a Hello World message
      operationId: getHello
      parameters:
        - name: alternateHello
          in: query
          description: Optional alternative to using the word 'Hello' in the reply
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A JSON structure containing a Hello World message
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloReply"
components:
  schemas:
  # https://swagger.io/specification/#schemaObject
    HelloReply:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Greeting from the API
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
